#!/usr/bin/env python3
"""The notice/short-form reference layer.

Atarashi's own license list carries one full text (plus an optional header) per
license. Real source files do not contain license bodies — they contain short
notices, and a notice sits at ~95% depth of a multi-thousand-token body, so
whole-document scoring never surfaces it. Measured on real headers, the
full-text-only layer scores R@1 ~0.004: it cannot identify them at all. Indexing
the short-form register alongside the bodies is what closes that gap, and it is
why ScanCode works in the wild.

The artifact is generated by ``scripts/build_references.py`` and committed, so
scancode-toolkit is a build-time dependency and never a runtime one. Its keys are
SPDX ids, so it is independent of both ScanCode's and FOSSology's internal naming;
this module maps them onto whatever shortnames the caller's license list uses.

SPDX-License-Identifier: GPL-2.0-only
"""
from __future__ import annotations

import json
from collections.abc import Iterable, Iterator
from pathlib import Path

from atarashi.libs.sequence import DEFAULT_MIN_RUN
from atarashi.spdx.resolver import lookup_shortname, shortname_index

DEFAULT_INDEX = Path(__file__).resolve().parents[1] / "data" / "licenses" / "notice_rules.json"


def load_notice_units(shortnames: Iterable[str],
                      path: Path | None = None,
                      min_tokens: int = DEFAULT_MIN_RUN) -> Iterator[tuple[str, str]]:
    """Yield ``(shortname, text)`` notice units for licenses the caller knows.

    Units keyed to a license absent from ``shortnames`` are dropped: the agent can
    only report licenses in its own list, so indexing the rest costs match time and
    buys nothing.

    Units shorter than ``min_tokens`` are dropped too. A match requires a contiguous
    run of at least ``DEFAULT_MIN_RUN`` tokens, so a shorter unit can never satisfy
    it — it is dead weight in the index, and the short units are generic filler
    ("licensed under a .") that could not attribute to one license anyway. The count
    is a whitespace split rather than the matcher's tokenizer: an approximation, but
    it avoids tokenizing 23k units twice at startup.

    Missing or unreadable artifact yields nothing rather than raising, so an agent
    built before the index exists still runs on the full-text layer alone.
    """
    index = shortname_index(shortnames)
    try:
        payload = json.loads(Path(path or DEFAULT_INDEX).read_text())
    except (OSError, ValueError):
        return
    for spdx, text in payload.get("units", ()):
        if len(text.split()) < min_tokens:
            continue
        shortname = lookup_shortname(spdx, index)
        if shortname is not None:
            yield shortname, text
